/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab;

public class App {
    
    public static void main(String[] args) {

        App app = new App();
        if(app.someAppMethod())
        System.out.println("Hello World");
    }

    public boolean someAppMethod() {
        return true;
    }
    public String getGreeting() {
        return "Hello World!";
    }
}
